name: CI
on: 
  push:
    branches:
      - main  # Set a branch to deploy
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "latest"
          extended: true

      - name: Clean public directory
        run: rm -rf public

      - name: Build
        run: hugo --minify --cleanDestinationDir --gc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          #external_repository: prmanna/tech-book
          publish_dir: ./public
          user_name: Prasenjit Manna
          user_email: prasenjit.manna@gmail.com
          publish_branch: publish
          cname: prasenjitmanna.com
